### ISSUE TITLE
Disable double/triple click detection

### ISSUE THREAD

**Issue by pablopeu** [LennartHennigs/Button2#44]
I'w writing a BT BLE keyboard to remotely control a machine via keyboard shortcuts, the most used keys are the arrows, and sometimes you click these a lot to get to the exact position. 
Is there a way to disable repetitive click to be detected as double/triple clicks? 
I can hack this by duplicating the detection and issuing double/triple the amount of keyboard taps on the respective handlers, but I guess a DEFINE would be far more elegant. Same for long press would be the icing in the cake :)

Thanks!

**Comment by LennartHennigs** [comment]
Hey @pablopeu,
thanks for the feedback. I added two compliler switches (_IGNORE_DOUBLE and _IGNORE_TRIPLE) to the code.
It is not in the released version yet, as I want to add a longpress switch as well. 
But if you download the latest version you can already use it.
Cheers
l.

**Comment by pablopeu** [comment]
Thanks a ton!

**Comment by LennartHennigs** [comment]
(Almost done - still have to do long click...) 
:-)
You are welcome.

**Comment by pablopeu** [comment]
While you are at it, with the disable longpress switch, will I be able to detect two/three keys pressed at once? Think of CTRL-ALT-DEL or CTRL-X when emulating a keyboard like I'm doing. Thanks

**Comment by LennartHennigs** [comment]
I knew you'd ask. 
Take a look at `TrackDualButtonClick`. Set flags for "special" keys and go from there. 
But if you do a real keyboard, I'd look for a keyboard matrix library instead, I think. Less pins to take care of.

**Comment by pablopeu** [comment]
You made me grin! Thanks again. Its not a full keyboard, just a few keys for a custom remote keyboard, trying to avoid complexity by not using a keyboard matrix.

**Comment by LennartHennigs** [comment]
done.

**Comment by pablopeu** [comment]
Hi, added the #define at the top of my program, downloaded latest library code, overwrited previous one, uploaded new code to ESP32 but doubleclicks do not behave like rapid single clicks, made a short video: [https://www.youtube.com/watch?v=b83OWDCFgO4](url)

**Comment by LennartHennigs** [comment]
Hey, try to uncomment the defines in the library itself.

**Comment by pablopeu** [comment]
Did it and saw the compilation messages about the routines not being compiled, but still doesn't catch a fast click, maybe its because Im reading 12 buttons, dunno.

**Comment by LennartHennigs** [comment]
Hey,
I think you don't see some of the "fast clicks" because of the thresholds for double and triple clicks are still there.
A way around this could be to use `setTapHandler()`.
This one is triggered on any click.

**Comment by pablopeu** [comment]
will look into it and let you know! Thanks Lennart

**Comment by pablopeu** [comment]
Did a quick test that worked, then did a find & replace on my full program: setClickHandler to setTapHandler and recompiled. Man, what a difference in responsiveness, its super fast on all the defined buttons (10 at this moment)

Thanks for the suggestion. BTW, is there a downside to using setTapHandler?

**Comment by LennartHennigs** [comment]
No. No downside. It does not respect the double or triple click timings. Thus, it reports clicks immediately.

**Comment by LennartHennigs** [comment]
pushed new version (2.1.0)

**Comment by LennartHennigs** [comment]
Hey, I decided to remove the compiler switches as the tap handler solves your question.  They only made the code more complex and did not really reduced the compiled code size.   
cheers

**Comment by pablopeu** [comment]
you're the boss!!! The tap handler did solve my issue. Thanks for all the help!!
